#!/usr/bin/env python3
"""Create deterministic, explicitly fictional delivery fixtures with no network use.

Each subject selects components that explain its own questions. All narratives,
dates, quantities and source records below are teaching material, not research.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import struct
import sys
from typing import Any, Dict, List
import zlib


AS_OF = "2026-10-08"
FICTION = "虚构教学样例；对象、记录、日期、数字与来源均为预设，不代表现实研究。"
KINDS = ("product", "industry", "company", "technology", "protocol", "policy", "person", "event")

# These authored teaching cases are stable input data, never generated by an LLM
# at runtime. Their distinct questions exercise the shared delivery contract.
CASES: Dict[str, Dict[str, Any]] = {
    "product": {
        "name": "栖光可换灯头台灯", "label": "产品", "accent": "#1A5276",
        "definition": "栖光是一款把灯头、灯臂和底座分开的虚构桌面照明产品，设定目标是让局部损坏可以单独处理。",
        "question": "换件便利能否抵消接口和备件维护的代价",
        "mechanism": "灯头经同一接口接入灯臂，用户保留底座、更换故障模块；接口寿命和备件供应随之成为约束。",
        "history": "早期设定采用整灯更换，拆装步骤很少，废弃部件却多。第二次设计把灯头独立出来，维修范围缩小，接触可靠性开始影响使用。到第三次修订，团队增加接口检查，但没有取得长期失效率记录。",
        "events": [("2024-03-01", "整灯替换", "以少步骤换取较多部件废弃。"), ("2025-04-01", "灯头分离", "维修范围缩小，接口成为新增约束。"), ("2026-09-01", "检查接口", "增加检查步骤，长期效果仍未知。")],
        "alternatives": [("整灯方案", "操作简单", "更换整灯", "部件废弃较多"), ("栖光方案", "局部维修", "维护接口与备件", "供应中断会失去优势"), ("固定维修点", "交由专人维修", "依赖服务网络", "等待与运输增加")],
        "inference": "早期模块化选择把今天的比较重点从购入价格移到接口寿命和备件可得性；只有这两项条件持续满足，局部维修才可能减少总负担。",
        "alternative": "维修次数很少时，接口与备件的维护负担可能高于节省。",
        "test": "同使用时长下的故障位置、接口失效和含备件的总维护负担。",
        "change": "若接口失效或备件缺货抵消局部维修收益，就撤回维护优势判断。",
        "components": ["images", "comparison", "calculator"],
    },
    "industry": {
        "name": "澄湾循环包装行业", "label": "行业", "accent": "#1E8449",
        "definition": "澄湾循环包装行业是虚构城镇中为商户提供容器投放、归还、清洗与再分配的一组服务活动。",
        "question": "归还密度如何改变价值链各环节的成本与协作",
        "mechanism": "容器只有完成归还、清洗和再次投放才形成循环；单次投放量不能代替实际循环次数。",
        "history": "分散商户各自回收时，清洗点离归还点很远。共享归还网络把容器集中，运输距离缩短，清洗排队成为新约束。随后出现预约分流，但虚构序列只记录处理量，没有记录全部运输和清洗负担。",
        "events": [("2024-03-01", "商户自收", "回收点分散。"), ("2025-04-01", "共享归还", "集中运输，清洗排队增加。"), ("2026-09-01", "预约分流", "调节到达时段，净效果未定。")],
        "alternatives": [("商户自收", "本店周转", "商户自行协调", "网络较碎"), ("共享网络", "跨店归还", "共同清洗调度", "高峰容易排队"), ("一次性包装", "即用即弃", "持续采购", "没有归还环节")],
        "inference": "共享归还的历史选择使行业竞争转向清洗与调度能力；较高处理量只说明流量通过，不能单独证明循环方案的净收益。",
        "alternative": "处理量增加也可能由补贴或商户数量增加驱动，和网络效率无关。",
        "test": "同服务范围、同容器寿命下的运输、清洗、损耗与实际循环次数。",
        "change": "若总负担没有下降，就收窄为归还便利改善，不推定行业整体效率提高。",
        "components": ["relationships", "series", "scenarios"],
        "network": ["归还网络", "商户", "清洗点"],
        "series": {"label": "示意处理量", "unit": "百次（虚构）", "values": [12, 18, 21]},
    },
    "company": {
        "name": "栈桥档案服务社", "label": "公司", "accent": "#5B2C6F",
        "definition": "栈桥档案服务社是一家虚构公司，帮助小型机构整理、描述和移交纸质档案。",
        "question": "从逐单定制转向共享工具后，交付速度和例外处理怎样变化",
        "mechanism": "公司把重复整理步骤固化为工具，由档案员处理无法套用规则的例外；规则覆盖与专业判断共同决定交付。",
        "history": "初期项目全部由档案员逐单处理。共享工具出现后，相同类型材料处理更快，但特殊材料不断退回人工。第三阶段给例外建立专门队列，完成量增加，人员构成也发生变化，因而不能把变化全算在工具上。",
        "events": [("2024-03-01", "逐单定制", "专业人员完成全部步骤。"), ("2025-04-01", "共享工具", "重复步骤统一，例外积累。"), ("2026-09-01", "例外队列", "分开处理特殊材料。")],
        "alternatives": [("栈桥服务", "规则与人工协作", "维护规则和例外队列", "覆盖范围有限"), ("项目工作室", "逐单适配", "依赖资深人员", "难以并行交付"), ("自建档案组", "内部持续维护", "机构自己投入人员", "需要稳定工作量")],
        "inference": "共享工具积累把公司优势限定在材料相近的项目；跨到例外很多的领域时，组织如何保留专业判断比完成量增长更有解释力。",
        "alternative": "完成量增长可能来自增员和较简单的项目组合，而非工具积累。",
        "test": "同类型材料、同人员投入下的处理时间与返工率。",
        "change": "若统一条件后速度优势消失，就撤回工具带来交付优势的推断。",
        "components": ["timeline", "comparison", "series"],
        "series": {"label": "示意完成量", "unit": "批（虚构）", "values": [8, 11, 16]},
    },
    "technology": {
        "name": "层窗采样技术", "label": "技术", "accent": "#2E86C1",
        "definition": "层窗采样是一种虚构信号处理技术，先以粗窗口筛查变化，再对候选窗口保留细节。",
        "question": "减少保存数据的同时会漏掉什么",
        "mechanism": "粗筛决定哪些片段进入细看；降低保存量的前提，是关键变化能触发粗筛，未触发的片段无法靠后续计算补回。",
        "history": "早期全量保留便于回查，却占用较多存储。加入粗筛后，保存量下降，短暂变化可能被遗漏。第三阶段保留随机抽检窗口，获得发现漏检的机会，但没有形成对所有信号类别都有效的证明。",
        "events": [("2024-03-01", "全量保留", "完整回查需要较多存储。"), ("2025-04-01", "粗筛窗口", "减少保存，新增漏检风险。"), ("2026-09-01", "随机抽检", "保留发现漏检的机会。")],
        "alternatives": [("全量保留", "完整回查", "持续存储", "资源占用较高"), ("层窗采样", "筛后留存", "依赖触发条件", "可能漏掉短变化"), ("固定间隔采样", "周期取样", "采样频率固定", "可能错过间隔事件")],
        "inference": "粗筛的历史选择决定了层窗采样的适用边界：资源收益必须和漏检一起测量；触发条件未经覆盖的信号不应沿用既有结论。",
        "alternative": "示例中的节省可能来自测试信号过于平稳，复杂信号会让多数窗口被保留。",
        "test": "覆盖短暂与连续变化的同一信号集上，测量漏检率和总资源占用。",
        "change": "漏检超过任务可承受范围时，撤回该任务中的适用判断。",
        "components": ["process", "evidence", "calculator"],
        "steps": [("粗窗筛查", "判断信号变化是否达到预设触发条件。"), ("细窗保留", "保留触发片段，记录未触发片段的抽检样本。"), ("核查遗漏", "将抽检结果与全量参照比较，更新适用范围。")],
    },
    "protocol": {
        "name": "信笺交换协议", "label": "协议", "accent": "#1A5276",
        "definition": "信笺交换协议是一份虚构的消息交换约定，用版本号、收件确认和重发规则协调发送端与接收端。",
        "question": "允许重发以后，如何避免把同一消息执行两次",
        "mechanism": "发送端保留消息标识，接收端记录处理结果；相同标识再次到达时返回原结果，这叫去重，效果取决于记录保留期限。",
        "history": "首版只约定消息格式，丢失确认时发送端不知道是否成功。加入重发后，丢失更容易恢复，重复执行成为新问题。第三版引入标识与保留期限，缩小重复范围，长期断连仍可能跨过这个期限。",
        "events": [("2024-03-01", "约定格式", "格式统一，处理状态未知。"), ("2025-04-01", "允许重发", "恢复丢失，可能重复执行。"), ("2026-09-01", "标识去重", "明确记录保留期限。")],
        "alternatives": [("信笺协议", "确认与重发", "接收端保留标识", "跨期限可能重复"), ("只发送一次", "避免主动重发", "容忍消息丢失", "无法自动恢复"), ("集中队列", "统一管理状态", "依赖队列服务", "增加部署环节")],
        "inference": "重发和去重的演变说明，当前兼容性需要共同理解保留期限；相同字段格式只证明能读消息，不能保证跨版本行为一致。",
        "alternative": "观察到的重复也可能来自应用绕过标识检查，不能全部归因于协议期限。",
        "test": "相同消息标识在正常、丢失确认和跨保留期限条件下的处理轨迹。",
        "change": "若双方对过期标识处理不同，就撤回这组版本可以直接互通的判断。",
        "components": ["process", "glossary", "relationships"],
        "steps": [("发送带标识消息", "保留消息标识和发送状态。"), ("检查已有结果", "接收端在保留期限内查询该标识。"), ("确认或重试", "返回原结果，未获确认时按约定重试。")],
        "network": ["信笺协议", "发送端", "接收端"],
        "terms": [("去重", "识别再次到达的同一消息并返回已记录结果。", "期限内相同标识返回原结果。", "字段能解析不代表已经去重。"), ("保留期限", "接收端保存标识和结果的时间范围。", "双方使用同一个约定期限。", "期限届满不能假定记录仍在。")],
    },
    "policy": {
        "name": "澄湾错峰装卸试行办法", "label": "政策", "accent": "#1E8449",
        "definition": "澄湾错峰装卸试行办法是一份虚构的地方规则，给试行街区分配装卸时段，并为特殊需求设置申请通道。",
        "question": "把装卸移出拥堵时段后，成本会转移给谁",
        "mechanism": "规则调整的是货车到达时段，商户收货与人员排班也要配合；道路变顺畅不等于所有参与者负担同时下降。",
        "history": "统一禁停减少了路面占用，却使小商户收货困难。预约时段给装卸留下入口，申请成本又影响参与。后续增加例外通道，规则更灵活，但执行一致性成为新的检验点。",
        "events": [("2024-03-01", "统一禁停", "路面占用减少，收货困难增加。"), ("2025-04-01", "预约时段", "安排入口，新增申请负担。"), ("2026-09-01", "例外通道", "兼顾特殊需求，执行一致性待查。")],
        "alternatives": [("统一禁停", "减少占道", "统一执法", "收货缺少入口"), ("错峰预约", "分配到达时段", "商户协调排班", "申请增加成本"), ("共享装卸区", "集中短停", "需要空间与调度", "步行搬运距离增加")],
        "inference": "例外通道来自早期统一规则的摩擦，因此当前评价必须同时查看道路与商户；只看通行改善，会遗漏转移到申请和排班中的负担。",
        "alternative": "道路通行变化可能来自同期车流减少，而非错峰安排。",
        "test": "相近日程和车流条件下的通行、收货延误、申请时间与例外处理差异。",
        "change": "若车流变化解释了通行改善，就撤回政策带来该改善的因果判断。",
        "components": ["timeline", "scenarios", "evidence"],
    },
    "person": {
        "name": "林澈的公共档案方法", "label": "人物", "accent": "#5B2C6F",
        "definition": "林澈是完全虚构的档案教育者，案例只讨论其预设公开作品中，从专家编目走向共同标注的方法变化。",
        "question": "开放参与怎样改变解释权与质量控制",
        "mechanism": "参与者可以提交标注，编辑记录出处与异议；参与人数增加不等于解释准确，保留分歧让后来的读者能够复查。",
        "history": "早期作品由专家给出统一条目，读者容易使用，却看不到不同解释。共同标注引入更多生活经验，也出现相互冲突的描述。后续作品保留出处与异议，林澈的工作从直接定论转向组织可复查的讨论。",
        "events": [("2024-03-01", "专家编目", "统一条目隐藏了部分分歧。"), ("2025-04-01", "共同标注", "多种经验进入条目。"), ("2026-09-01", "保留异议", "把解释过程留给读者复查。")],
        "alternatives": [("林澈的预设路线", "共同标注并保留异议", "维护出处与讨论", "阅读负担增加"), ("专家主编路线", "统一解释", "集中审定", "参与渠道较少"), ("自由注释路线", "开放添加", "读者自行判断", "冲突不易处理")],
        "inference": "从给出答案到保留异议的转折，使林澈与其他路线的差异落在解释权安排；不能把开放姿态直接当成成果质量更高。",
        "alternative": "作品变化可能来自合作编辑的要求，未必代表林澈个人立场已经转变。",
        "test": "同一类材料中署名、编辑过程及本人公开说明是否一致。",
        "change": "若变化主要由他人制定，就收窄为作品流程变化，不归因于个人思想转折。",
        "components": ["timeline", "evidence", "glossary"],
        "terms": [("共同标注", "多位参与者为同一材料补充解释并记录出处。", "同一条目保留不同观察。", "参与者多不代表意见已经一致。"), ("解释权", "决定哪些解释被保存、展示和修订的安排。", "编辑留下修改理由供人复查。", "公开留言并不自动改变审定权限。")],
    },
    "event": {
        "name": "澄湾步行桥临时关闭事件", "label": "事件", "accent": "#2E86C1",
        "definition": "澄湾步行桥临时关闭事件是一段虚构的公共设施应对过程，围绕异常报告、临时绕行和条件复开展开。",
        "question": "信息不齐时采取临时措施，怎样区分决定依据与事后结果",
        "mechanism": "维护组收到异常报告后设置临时绕行，检查组补充观察；措施是否合理要对照当时可知信息，复开也需要明确条件。",
        "history": "异常报告出现时，现场原因尚未确定，管理方先限制通行。临时绕行降低了桥面使用，却增加周边路程。检查记录逐步补齐后才讨论复开，报告时间与检查时间不能合并成同一个已知时点。",
        "events": [("2026-09-01", "异常报告", "原因未定，先记录可见现象。"), ("2026-09-02", "临时绕行", "限制通行，保留检查窗口。"), ("2026-09-05", "条件复核", "核对检查结果和复开条件。")],
        "alternatives": [("全面关闭", "减少桥面使用", "安排远距离绕行", "出行负担较大"), ("分时限制", "控制使用强度", "需要现场管理", "剩余不确定性较多"), ("条件复开", "逐项核查后恢复", "持续观察", "依赖条件可测量")],
        "inference": "临时关闭给检查留出了时间，但绕行代价也随之产生；评价这次选择，需要把当时未知、后来发现和可行替代分开。",
        "alternative": "绕行拥堵可能由同期道路施工造成，不能直接认定全部来自关闭。",
        "test": "带时间戳的报告、检查、交通变化及当时可执行的替代方案。",
        "change": "若后来证据被误写成决策时已知信息，就重写对当时选择的评价。",
        "components": ["timeline", "relationships", "scenarios"],
        "network": ["维护组", "检查组", "通行者"],
    },
}


def component(kind: str, case: Dict[str, Any], subject_kind: str) -> Dict[str, Any]:
    titles = {"timeline": "选择怎样带来新约束", "comparison": "路线按同一问题比较", "process": "机制在哪一步受约束",
              "relationships": "参与者如何连接", "scenarios": "条件变化会怎样改变判断", "evidence": "支持范围与反方一起看",
              "images": "栖光的虚构结构示意", "glossary": "容易混淆的概念", "series": "预设序列只说明示意变化", "calculator": "调整假设，查看线性预算"}
    value: Dict[str, Any] = {"id": subject_kind + "-" + kind, "kind": kind, "title": titles[kind],
                             "intro": FICTION, "source_ids": ["S001", "S002"]}
    if kind == "timeline":
        value["events"] = [{"id": "stage-" + str(i + 1), "date": date, "label": label, "detail": detail, "category": "虚构记录"}
                           for i, (date, label, detail) in enumerate(case["events"])]
    elif kind == "comparison":
        value["columns"] = [{"id": "goal", "label": "回应的目标"}, {"id": "condition", "label": "依赖条件"}, {"id": "cost", "label": "代价或边界"}]
        value["rows"] = [{"id": "route-" + str(i + 1), "label": name, "values": {"goal": goal, "condition": condition, "cost": cost}, "detail": "虚构路线，按同一任务比较，不构成推荐。"}
                         for i, (name, goal, condition, cost) in enumerate(case["alternatives"])]
    elif kind == "process":
        value["steps"] = [{"id": "step-" + str(i + 1), "title": title, "body": body} for i, (title, body) in enumerate(case["steps"])]
    elif kind == "relationships":
        value["nodes"] = [{"id": "node-" + str(i + 1), "label": label, "detail": "虚构设定中承担协作环节的角色。"} for i, label in enumerate(case["network"])]
        labels = {"industry": ("组织归还", "安排清洗"), "protocol": ("约定发送", "约定接收"), "event": ("请求检查", "通知绕行")}
        value["links"] = [{"from": "node-1", "to": "node-2", "label": labels[subject_kind][0], "kind": "fact"},
                          {"from": "node-1", "to": "node-3", "label": labels[subject_kind][1], "kind": "fact"}]
    elif kind == "scenarios":
        value["cases"] = [
            {"id": "condition-holds", "title": "关键条件得到支持", "when": "取得可区分解释的同条件记录。", "text": case["inference"], "outcomes": [{"label": "判断范围", "value": "保留为有条件判断"}], "limitation": "虚构条件推演，没有概率或现实预测。"},
            {"id": "alternative-holds", "title": "替代解释获得支持", "when": case["test"], "text": case["alternative"], "outcomes": [{"label": "修订方式", "value": case["change"]}], "limitation": "选择情景只改变展示内容，不代表已经观测到结果。"},
        ]
    elif kind == "evidence":
        value["items"] = [{"id": "defined-mechanism", "title": "设定中的机制", "statement": case["mechanism"], "limit": "来自教学设定，未通过真实原文或观测核验。", "kind": "虚构设定"},
                          {"id": "strong-alternative", "title": "最强合理替代", "statement": case["alternative"], "limit": case["test"], "kind": "待区分解释"}]
        value["conclusion"] = case["change"]
    elif kind == "images":
        value["items"] = [{"id": "lamp-diagram", "path": "images/lamp-diagram.png", "alt": "虚构台灯结构示意", "caption": "脚本原生绘制的虚构结构，非产品实拍；三个部件仅用于解释局部更换。", "points": [
            {"x": 66, "y": 26, "title": "可换灯头", "body": "虚构灯头可单独更换；未提供真实尺寸或寿命。"},
            {"x": 47, "y": 43, "title": "连接位置", "body": "接口使更换成为可能，也引入接触可靠性的约束。"},
            {"x": 40, "y": 77, "title": "保留底座", "body": "维修时保留底座是教学设定，不代表经过验证的材料节省。"},
        ]}]
    elif kind == "glossary":
        value["items"] = [{"id": "term-" + str(i + 1), "term": term, "definition": definition, "example": example, "counterexample": counterexample}
                          for i, (term, definition, example, counterexample) in enumerate(case["terms"])]
    elif kind == "series":
        value.update({"mode": "line", "unit": case["series"]["unit"], "basis": "2024—2026 每年同一截面标签的预设数字；不含净成本或因果对照。",
                      "x": ["2024", "2025", "2026"], "series": [{"id": "fictional-volume", "label": case["series"]["label"], "values": case["series"]["values"]}]})
    elif kind == "calculator":
        if subject_kind == "product":
            value["inputs"] = [{"id": "modules", "label": "示意备件数", "value": 2, "min": 0, "max": 10, "step": 1, "unit": "件"},
                               {"id": "hours", "label": "示意维护时长", "value": 3, "min": 0, "max": 20, "step": 1, "unit": "小时"}]
            value["outputs"] = [{"id": "budget", "label": "示意总预算", "unit": "虚构记账点", "base": 100, "terms": [{"input": "modules", "coefficient": 25}, {"input": "hours", "coefficient": 8}]}]
            value["assumptions"] = "固定基础100点，每件备件25点、每小时维护8点，全部为虚构线性系数；未计停机、运输或备件缺货，不能作购买建议。"
        else:
            value["inputs"] = [{"id": "channels", "label": "示意通道数", "value": 4, "min": 1, "max": 12, "step": 1, "unit": "路"},
                               {"id": "buffer", "label": "示意缓存容量", "value": 8, "min": 0, "max": 32, "step": 1, "unit": "MB"}]
            value["outputs"] = [{"id": "memory", "label": "示意内存预算", "unit": "MB（虚构）", "base": 4, "terms": [{"input": "channels", "coefficient": 2}, {"input": "buffer", "coefficient": 1}]}]
            value["assumptions"] = "固定基础4MB，每通道2MB，加设定缓存容量；全部为虚构系数。未建模采样频率与漏检，预算变化不能证明技术效果。"
    else:
        raise ValueError("unsupported component kind: " + kind)
    return value


def sources_for(kind: str, case: Dict[str, Any]) -> Dict[str, Any]:
    claims: List[Dict[str, Any]] = [
        {"id": "C001", "claim": case["definition"], "source_ids": ["S001"], "status": "provisional", "confidence": "low"},
        {"id": "C002", "claim": "虚构演变记录：" + case["history"], "source_ids": ["S001"], "status": "provisional", "confidence": "low"},
        {"id": "C003", "claim": "虚构比较围绕“" + case["question"] + "”统一任务，不能把预设结果当成测量。", "source_ids": ["S002"], "status": "provisional", "confidence": "low"},
        {"id": "C004", "claim": "教学推断：" + case["inference"], "source_ids": ["S001", "S002"], "status": "provisional", "confidence": "low", "kind": "inference",
         "impact_reason": "该推断决定读者如何解释演变与当前路线差异；本样例仅验证记录和交付结构。",
         "evidence": [{"source_id": "S001", "locator": "虚构设定稿：机制与三次选择；无真实原文。", "supported_statement": case["mechanism"], "support_boundary": "只记录教学设定，不证明现实效果。", "time_basis": "设定记录截至2026-09-30，回顾此前虚构节点。"},
                      {"source_id": "S002", "locator": "虚构对照稿：同任务路线与反方；无真实原文。", "supported_statement": "比较保留各路线的依赖条件与代价。", "support_boundary": case["alternative"], "time_basis": "对照标签2026-09-30，没有实际测量窗口。"}],
         "review": {"alternative": case["alternative"], "discriminating_evidence": case["test"], "change_condition": case["change"], "revision": "将无条件优势收窄为有适用条件的教学推断，保留替代解释。"}},
    ]
    sources = []
    for sid, title, supports in [("S001", "虚构设定与演变稿", ["C001", "C002", "C004"]), ("S002", "虚构路线与数据对照稿", ["C003", "C004", "D001"])]:
        sources.append({"id": sid, "display_name": title, "title": case["name"] + "：" + title, "url": "https://example.invalid/fictional/" + kind + "/" + sid.lower(),
                        "publisher": "虚构教学编辑组", "published_at": "2026-09-30", "accessed_at": AS_OF, "language": "zh-CN", "region": "虚构地域", "perspective_group": "虚构教学", "tier": 3, "type": "fictional",
                        "supports": supports, "independence_key": "fictional-" + kind,
                        "notes": "虚构来源，无真实原文，也没有联网访问；URL为保留的.invalid域名。日期和tier字段只是结构演示，不是真实可靠性评级。两稿来自同一设定，不能视为独立证据。产品结构图由本脚本绘制，只是示意。"})
    return {"method_version": "3", "as_of": AS_OF, "coverage": {"balance_policy": "diagnostic", "attempted_languages": [], "attempted_regions": [], "attempted_platforms": [], "successful_source_categories": [], "successful_domains": [], "blocked_domains": [], "network_limitations": [], "target_perspective_groups": ["虚构教学"], "balance_exception": None, "notes": FICTION + "未检索任何真实来源；元数据只验证结构。"},
            "limitations": [{"scope": "全部正文、组件、图片、来源与数据", "cause": "确定性脚本中的虚构教学设定，没有真实检索或实际观测。", "bias": "无法代表现实对象，也不能证明研究方法的效果。", "affected_claims": ["C001", "C002", "C003", "C004", "D001"], "confidence": "low"}],
            "sources": sources, "claims": claims, "datasets": [{"id": "D001", "file": "data/components.json", "unit": "组件内声明的虚构单位；定性项没有数量单位", "definition": "人工预设的教学组件内容和参数，所有数值、日期和角色均虚构。", "period": "虚构标签2024-03-01至2026-09-30", "geography": "虚构地域", "source_ids": ["S002"]}]}


def report_for(case: Dict[str, Any], kind: str) -> str:
    image = ""
    if kind == "product":
        image = '\n::: representative-images\n![虚构台灯示意](images/lamp-diagram.png)\n:::\n<span class="figure-source">图片：脚本原生绘制，2026-10-08；仅为虚构结构示意。{{@S001 | 没有对应实物，不能用于核验产品外观或性能。}}</span>\n'
    rows = "\n".join("| " + " | ".join(row) + " |" for row in case["alternatives"])
    return "\n\n".join([
        "# " + case["name"] + "：虚构教学样例",
        "> 研究截面：" + AS_OF + "｜范围：虚构教学｜对象类型：" + case["label"],
        "## 一、一句话定义", case["definition"] + "{{@S001 | 定义和对象均出自虚构设定。}}" + image,
        "### 执行摘要", "这份小型样例帮助读者练习解释“" + case["question"] + "”。" + case["mechanism"] + "关键记录均为虚构，当前只能展示有条件的推断，不能据此做现实选择。{{@S001,@S002 | 教学设定不构成现实证据。}}",
        "### 研究范围与限制", FICTION + "没有开展真实检索，来源地址不可作为实际原文。图和交互参数只能检验表达与构建，不能证明对象存在、结论成立或方法有效。",
        "核心阅读可从“三、横向分析：路线与代价”进入，再回到“四、横纵交汇洞察”核对判断条件；深入阅读包括纵向转折和方法说明。",
        "## 二、纵向分析：从选择到新约束", case["history"] + "{{@S001 | 日期与节点是教学标签，均早于研究截面。}}",
        "这些节点的意义在于约束怎样改变。" + case["mechanism"] + "下一节据此比较能回应相同问题的路线。{{@S001 | 机制用于说明设定内部的关系，未经现实验证。}}",
        "## 三、横向分析：路线与代价", "候选路线按同一任务纳入，比较目标、依赖条件和代价；不把不同用途的对象放进一张排名表。{{@S002 | 定性比较，无现实评分。}}",
        "| 路线 | 回应的目标 | 依赖条件 | 代价或边界 |\n|---|---|---|---|\n" + rows,
        "表内差异揭示了选择需要承担什么，却没有给出所有条件下的优胜者。" + case["alternative"] + "{{@S002 | 反方与当前判断保留在同一比较口径中。}}",
        "## 四、横纵交汇洞察", case["inference"] + "{{@S001,@S002 | 这是连接历史与当前差异的教学推断。}}",
        "要区分这项推断与替代解释，需要取得：" + case["test"] + "本样例没有这类真实证据。" + case["change"] + "{{@S002 | 未知保留为未知，不因组件完整而提高可信度。}}",
        "## 五、信息来源与方法说明", "正文和交互组件复用同一来源台账；两个虚构来源来自同一教学设定，不构成独立印证。所有来源、数字与示意图均明确虚构，只用于验证纵向、横向和交汇内容能否进入同一交付流程。",
    ]) + "\n"


def write_lamp_png(path: Path) -> None:
    """Draw an original schematic using only standard-library RGB PNG output."""
    width, height = 1000, 600
    pixels = bytearray((244, 246, 247) * width * height)

    def rect(x1: int, y1: int, x2: int, y2: int, color: tuple) -> None:
        for y in range(max(0, y1), min(height, y2)):
            start, end = 3 * (y * width + max(0, x1)), 3 * (y * width + min(width, x2))
            pixels[start:end] = bytes(color) * ((end - start) // 3)

    def circle(cx: int, cy: int, radius: int, color: tuple) -> None:
        for y in range(max(0, cy - radius), min(height, cy + radius + 1)):
            extent = int(max(0, radius * radius - (y - cy) ** 2) ** 0.5)
            rect(cx - extent, y, cx + extent + 1, y + 1, color)

    def line(x1: int, y1: int, x2: int, y2: int, radius: int, color: tuple) -> None:
        steps = max(abs(x2 - x1), abs(y2 - y1))
        for i in range(steps + 1):
            circle(round(x1 + (x2 - x1) * i / max(1, steps)), round(y1 + (y2 - y1) * i / max(1, steps)), radius, color)

    navy, green, blue, light = (26, 82, 118), (30, 132, 73), (46, 134, 193), (225, 233, 237)
    rect(70, 490, 930, 497, light)
    rect(272, 445, 528, 475, navy)
    circle(287, 459, 15, navy)
    circle(513, 459, 15, navy)
    line(400, 444, 355, 330, 15, navy)
    line(355, 330, 470, 258, 15, navy)
    circle(355, 330, 24, green)
    circle(355, 330, 10, light)
    line(470, 258, 534, 181, 10, navy)
    circle(470, 258, 21, green)
    circle(470, 258, 9, light)
    rect(522, 133, 780, 174, blue)
    rect(534, 174, 770, 185, green)
    # Dashed correspondence lines identify the modular connector in a schematic.
    for x in range(552, 760, 26):
        rect(x, 212, x + 13, 216, light)
    scanlines = b"".join(b"\x00" + bytes(pixels[y * width * 3:(y + 1) * width * 3]) for y in range(height))

    def chunk(tag: bytes, payload: bytes) -> bytes:
        return struct.pack(">I", len(payload)) + tag + payload + struct.pack(">I", zlib.crc32(tag + payload) & 0xffffffff)

    path.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(scanlines, 9)) + chunk(b"IEND", b""))


def create_fixture(kind: str, destination: Path) -> Dict[str, Any]:
    if kind not in CASES:
        raise ValueError("unknown fixture kind: " + kind)
    if destination.is_symlink():
        raise ValueError("destination must not be a symbolic link")
    destination = destination.resolve()
    if destination.exists() and (not destination.is_dir() or any(destination.iterdir())):
        raise ValueError("destination must be absent or an empty directory: " + str(destination))
    destination.mkdir(parents=True, exist_ok=True)
    for folder in ("sources", "data"):
        (destination / folder).mkdir()
    case = CASES[kind]
    if kind == "product":
        (destination / "images").mkdir()
        write_lamp_png(destination / "images/lamp-diagram.png")
    study = {"version": 1, "id": "fictional-" + kind, "title": case["name"] + "：虚构教学样例", "subtitle": FICTION,
             "subject_type": kind, "as_of": AS_OF, "report": "report.md", "sources": "sources/sources.json", "components": "data/components.json",
             "theme": {"accent": case["accent"], "source": "主题编辑选择，非官方品牌色"}}
    files = {"study.json": study, "sources/sources.json": sources_for(kind, case),
             "data/components.json": {"version": 1, "components": [component(item, case, kind) for item in case["components"]]}}
    for relative, value in files.items():
        with (destination / relative).open("w", encoding="utf-8", newline="\n") as handle:
            handle.write(json.dumps(value, ensure_ascii=False, indent=2) + "\n")
    with (destination / "report.md").open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(report_for(case, kind))
    return {"status": "created", "kind": kind, "workspace": str(destination), "study": str(destination / "study.json"),
            "component_kinds": case["components"], "fictional": True}


def main(argv: List[str] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kind", choices=KINDS, required=True)
    parser.add_argument("--destination", type=Path, required=True, help="Absent or empty destination directory; never overwrite existing content.")
    args = parser.parse_args(argv)
    try:
        result = create_fixture(args.kind, args.destination)
    except (OSError, ValueError) as exc:
        print(json.dumps({"status": "error", "error": str(exc)}, ensure_ascii=False), file=sys.stderr)
        return 1
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
